services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-backend
    volumes:
      - ./backend/users.db:/app/users.db
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  app-network:
    driver: bridge