name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/gestionutili

    steps:
    # 1. ✅ Checkout du repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. ✅ Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. ✅ Installation des dépendances
    - name: Install dependencies
      run: npm ci

    # 4. ✅ Lancement des tests
    - name: Run backend tests
      run: |
        cd backend
        npm install
        npm test

    # 5. ✅ Build Docker image
    - name: Build Docker image
      run: docker build -t $DOCKER_IMAGE:latest .

    # 6. ✅ Push image vers Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push $DOCKER_IMAGE:latest
